---

- hosts: all
  tasks:
    - shell: whoami
      register: whoami

    - debug: msg={{ whoami }}

- hosts: anhpnv
  tasks:
  - name: Install Nginx
    apt:
      name: nginx
  - name: Add index.html
    become: true
    copy:
      src: index.html
      dest: /var/www/html